// Copyright 2025 Zileo-Chat-3 Contributors
// SPDX-License-Identifier: Apache-2.0

use crate::mcp::MCPManager;
use crate::models::{AgentConfig, Lifecycle};
use async_trait::async_trait;
use std::sync::Arc;

/// Task represents a request to the agent
#[derive(Debug, Clone)]
pub struct Task {
    /// Unique task identifier
    pub id: String,
    /// Task description
    pub description: String,
    /// Additional context
    pub context: serde_json::Value,
}

/// Report generated by an agent (Markdown format)
#[derive(Debug, Clone)]
pub struct Report {
    /// Task identifier (used in future phases for tracking)
    #[allow(dead_code)]
    pub task_id: String,
    /// Report status
    pub status: ReportStatus,
    /// Markdown content
    pub content: String,
    /// Execution metrics
    pub metrics: ReportMetrics,
}

/// Report status
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum ReportStatus {
    Success,
    Failed,
    Partial,
}

/// Metrics collected during task execution
#[derive(Debug, Clone)]
pub struct ReportMetrics {
    /// Duration in milliseconds
    pub duration_ms: u64,
    /// Input tokens consumed
    pub tokens_input: usize,
    /// Output tokens generated
    pub tokens_output: usize,
    /// Tools used
    pub tools_used: Vec<String>,
    /// MCP calls made
    pub mcp_calls: Vec<String>,
}

/// Agent trait - unified interface for all agents
#[async_trait]
#[allow(dead_code)]
pub trait Agent: Send + Sync {
    /// Executes a task and returns a report
    ///
    /// This is the legacy method without MCP support.
    /// New implementations should prefer `execute_with_mcp`.
    async fn execute(&self, task: Task) -> anyhow::Result<Report>;

    /// Executes a task with access to MCP tools
    ///
    /// This method allows the agent to call MCP tools during execution.
    /// The default implementation delegates to `execute()` for backward compatibility.
    ///
    /// # Arguments
    /// * `task` - The task to execute
    /// * `mcp_manager` - Optional MCP manager for tool invocation
    ///
    /// # Returns
    /// A report containing the execution results and metrics
    async fn execute_with_mcp(
        &self,
        task: Task,
        _mcp_manager: Option<Arc<MCPManager>>,
    ) -> anyhow::Result<Report> {
        // Default implementation for backward compatibility
        self.execute(task).await
    }

    /// Returns agent capabilities
    fn capabilities(&self) -> Vec<String>;

    /// Returns lifecycle type
    fn lifecycle(&self) -> Lifecycle;

    /// Returns available tools
    fn tools(&self) -> Vec<String>;

    /// Returns required MCP servers
    fn mcp_servers(&self) -> Vec<String>;

    /// Returns system prompt
    fn system_prompt(&self) -> String;

    /// Returns agent configuration
    fn config(&self) -> &AgentConfig;
}
