// Copyright 2025 Assistance Micro Design
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::models::mcp::{MCPCallLogCreate, MCPDeploymentMethod, MCPServerConfig, MCPServerCreate};
use std::collections::HashMap;

fn create_test_config(id: &str, name: &str) -> MCPServerConfig {
    MCPServerConfig {
        id: id.to_string(),
        name: name.to_string(),
        enabled: true,
        command: MCPDeploymentMethod::Docker,
        args: vec![
            "run".to_string(),
            "-i".to_string(),
            "test:latest".to_string(),
        ],
        env: HashMap::new(),
        description: Some("Test server".to_string()),
        auth_type: None,
        auth_metadata: None,
        extra_headers: None,
    }
}

#[test]
fn test_server_config_creation() {
    let config = create_test_config("test_id", "test_server");
    assert_eq!(config.id, "test_id");
    assert_eq!(config.name, "test_server");
    assert!(config.enabled);
}

#[test]
fn test_mcp_server_create_from_config() {
    let config = create_test_config("test_id", "test_server");
    let create = MCPServerCreate::from_config(&config);

    assert_eq!(create.name, "test_server");
    assert_eq!(create.command, "docker");
    assert!(create.enabled);
}

#[test]
fn test_call_log_serialization() {
    // Test MCPCallLogCreate serialization (timestamp omitted - generated by SurrealDB)
    let log = MCPCallLogCreate {
        id: "log_123".to_string(),
        workflow_id: Some("wf_456".to_string()),
        server_name: "serena".to_string(),
        tool_name: "find_symbol".to_string(),
        params: serde_json::json!({"name": "MyClass"}),
        result: serde_json::json!({"found": true}),
        success: true,
        duration_ms: 150,
    };

    let json = serde_json::to_string(&log).unwrap();
    assert!(json.contains("\"server_name\":\"serena\""));
    assert!(json.contains("\"tool_name\":\"find_symbol\""));
    assert!(json.contains("\"success\":true"));
    // Verify timestamp is NOT in the serialized output
    assert!(!json.contains("\"timestamp\":"));
}
