/**
 * Copyright 2025 Assistance Micro Design
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Sub-Agent System Types
 *
 * Types for the sub-agent execution system, synchronized with Rust models
 * in `src-tauri/src/models/sub_agent.rs`.
 *
 * @module types/sub-agent
 */

/**
 * Status of a sub-agent execution.
 *
 * Tracks the lifecycle of a sub-agent from creation to completion.
 */
export type SubAgentStatus =
  | 'pending'
  | 'running'
  | 'completed'
  | 'error'
  | 'cancelled';

/**
 * Sub-agent execution record from database.
 *
 * Tracks a single sub-agent execution including timing, metrics, and results.
 */
export interface SubAgentExecution {
  /** Unique identifier */
  id: string;
  /** Workflow ID where this execution occurred */
  workflow_id: string;
  /** ID of the parent (primary) agent that spawned/delegated */
  parent_agent_id: string;
  /** ID of the sub-agent performing the task */
  sub_agent_id: string;
  /** Human-readable name of the sub-agent */
  sub_agent_name: string;
  /** Description of the task assigned to the sub-agent */
  task_description: string;
  /** Current execution status */
  status: SubAgentStatus;
  /** Execution duration in milliseconds */
  duration_ms?: number;
  /** Input tokens consumed by the sub-agent */
  tokens_input?: number;
  /** Output tokens generated by the sub-agent */
  tokens_output?: number;
  /** Summary of the sub-agent's report (truncated for storage) */
  result_summary?: string;
  /** Error message if status is 'error' */
  error_message?: string;
  /** Parent execution ID for hierarchical tracing (e.g., batch operations) */
  parent_execution_id?: string;
  /** ISO timestamp when the execution was created */
  created_at: string;
  /** ISO timestamp when the execution completed (if completed) */
  completed_at?: string;
}

// =============================================================================
// Validation Types for Human-in-the-Loop
// =============================================================================

import type { RiskLevel } from './validation';

/**
 * Validation required event payload.
 * Emitted by backend when an operation needs user approval.
 * Supports all validation types: sub_agent, tool, mcp, file_op, db_op.
 */
export interface ValidationRequiredEvent {
  /** Validation request ID (for approve/reject calls) */
  validation_id: string;
  /** Associated workflow ID */
  workflow_id: string;
  /** Validation type (e.g. "sub_agent", "tool", "mcp", "file_op", "db_op") */
  validation_type: string;
  /** Human-readable operation description */
  operation: string;
  /** Risk level assessment */
  risk_level: RiskLevel;
  /** Additional details about the operation (structure varies by type) */
  details: Record<string, unknown>;
}

