/**
 * Copyright 2025 Assistance Micro Design
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Copyright 2025 Zileo-Chat-3 Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Sub-Agent System Types
 *
 * Types for the sub-agent execution system, synchronized with Rust models
 * in `src-tauri/src/models/sub_agent.rs`.
 *
 * @module types/sub-agent
 */

/**
 * Status of a sub-agent execution.
 *
 * Tracks the lifecycle of a sub-agent from creation to completion.
 */
export type SubAgentStatus =
  | 'pending'
  | 'running'
  | 'completed'
  | 'error'
  | 'cancelled';

/**
 * Sub-agent execution record from database.
 *
 * Tracks a single sub-agent execution including timing, metrics, and results.
 */
export interface SubAgentExecution {
  /** Unique identifier */
  id: string;
  /** Workflow ID where this execution occurred */
  workflow_id: string;
  /** ID of the parent (primary) agent that spawned/delegated */
  parent_agent_id: string;
  /** ID of the sub-agent performing the task */
  sub_agent_id: string;
  /** Human-readable name of the sub-agent */
  sub_agent_name: string;
  /** Description of the task assigned to the sub-agent */
  task_description: string;
  /** Current execution status */
  status: SubAgentStatus;
  /** Execution duration in milliseconds */
  duration_ms?: number;
  /** Input tokens consumed by the sub-agent */
  tokens_input?: number;
  /** Output tokens generated by the sub-agent */
  tokens_output?: number;
  /** Summary of the sub-agent's report (truncated for storage) */
  result_summary?: string;
  /** Error message if status is 'error' */
  error_message?: string;
  /** ISO timestamp when the execution was created */
  created_at: string;
  /** ISO timestamp when the execution completed (if completed) */
  completed_at?: string;
}

/**
 * Metrics from a sub-agent execution.
 *
 * Returned as part of the tool result to the primary agent.
 */
export interface SubAgentMetrics {
  /** Execution duration in milliseconds */
  duration_ms: number;
  /** Input tokens consumed */
  tokens_input: number;
  /** Output tokens generated */
  tokens_output: number;
}

/**
 * Result of a sub-agent spawn operation.
 *
 * Returned by SpawnAgentTool after successful execution.
 */
export interface SubAgentSpawnResult {
  /** Whether the spawn was successful */
  success: boolean;
  /** ID of the spawned sub-agent */
  child_id: string;
  /** Markdown report from the sub-agent */
  report: string;
  /** Execution metrics */
  metrics: SubAgentMetrics;
}

/**
 * Result of a delegate operation.
 *
 * Returned by DelegateTaskTool after successful delegation.
 */
export interface DelegateResult {
  /** Whether the delegation was successful */
  success: boolean;
  /** ID of the delegated-to agent */
  agent_id: string;
  /** Markdown report from the agent */
  report: string;
  /** Execution metrics */
  metrics: SubAgentMetrics;
}

/**
 * Result of a single task in a parallel batch.
 */
export interface ParallelTaskResult {
  /** Agent ID that executed the task */
  agent_id: string;
  /** Whether this task succeeded */
  success: boolean;
  /** Report from the agent (if successful) */
  report?: string;
  /** Error message (if failed) */
  error?: string;
  /** Execution metrics (if available) */
  metrics?: SubAgentMetrics;
}

/**
 * Result of a parallel batch execution.
 *
 * Returned by ParallelTasksTool after executing multiple tasks.
 */
export interface ParallelBatchResult {
  /** Whether all tasks completed successfully */
  success: boolean;
  /** Number of tasks that completed successfully */
  completed: number;
  /** Number of tasks that failed */
  failed: number;
  /** Individual results for each task */
  results: ParallelTaskResult[];
  /** Aggregated report from all tasks */
  aggregated_report: string;
}

/**
 * Streaming event types for sub-agent operations.
 */
export type SubAgentEventType =
  | 'sub_agent_start'
  | 'sub_agent_progress'
  | 'sub_agent_complete'
  | 'sub_agent_error';

/**
 * Streaming event payload for sub-agent operations.
 *
 * Emitted via Tauri events to update the frontend in real-time.
 */
export interface SubAgentStreamEvent {
  /** Type of the event */
  type: SubAgentEventType;
  /** Workflow ID */
  workflow_id: string;
  /** Parent agent ID */
  parent_agent_id: string;
  /** Sub-agent ID */
  sub_agent_id: string;
  /** Sub-agent name */
  sub_agent_name: string;
  /** Event-specific data */
  data?: {
    /** Report from sub-agent (on complete) */
    report?: string;
    /** Error message (on error) */
    error?: string;
    /** Execution metrics (on complete) */
    metrics?: SubAgentMetrics;
    /** Progress percentage (on progress) */
    progress?: number;
  };
}

/**
 * Constants for sub-agent system.
 */
export const SUB_AGENT_CONSTANTS = {
  /** Maximum number of sub-agents per workflow */
  MAX_SUB_AGENTS: 3,
  /** Maximum length for task descriptions */
  MAX_TASK_DESCRIPTION_LEN: 10000,
  /** Maximum length for result summaries */
  MAX_RESULT_SUMMARY_LEN: 5000,
} as const;

/**
 * Sub-agent stream event names for Tauri listeners.
 */
export const SUB_AGENT_EVENTS = {
  /** Event emitted when a sub-agent starts execution */
  SUB_AGENT_START: 'sub_agent_start',
  /** Event emitted for sub-agent progress updates */
  SUB_AGENT_PROGRESS: 'sub_agent_progress',
  /** Event emitted when a sub-agent completes */
  SUB_AGENT_COMPLETE: 'sub_agent_complete',
  /** Event emitted when a sub-agent encounters an error */
  SUB_AGENT_ERROR: 'sub_agent_error',
} as const;

// =============================================================================
// Validation Types for Human-in-the-Loop
// =============================================================================

/**
 * Type of sub-agent operation requiring validation.
 * Matches Rust SubAgentOperationType in streaming.rs.
 */
export type SubAgentOperationType = 'spawn' | 'delegate' | 'parallel_batch';

/**
 * Risk level for validation requests.
 * Matches Rust RiskLevel in validation.rs.
 */
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

/**
 * Validation required event payload.
 * Emitted by backend when a sub-agent operation needs user approval.
 */
export interface ValidationRequiredEvent {
  /** Validation request ID (for approve/reject calls) */
  validation_id: string;
  /** Associated workflow ID */
  workflow_id: string;
  /** Type of sub-agent operation */
  operation_type: SubAgentOperationType;
  /** Human-readable operation description */
  operation: string;
  /** Risk level assessment */
  risk_level: RiskLevel;
  /** Additional details about the operation */
  details: {
    /** Sub-agent name (for spawn) */
    sub_agent_name?: string;
    /** Prompt preview (truncated) */
    prompt_preview?: string;
    /** Full prompt length */
    prompt_length?: number;
    /** Tools requested */
    tools?: string[];
    /** MCP servers requested */
    mcp_servers?: string[];
    /** Target agent ID (for delegate) */
    target_agent_id?: string;
    /** Target agent name (for delegate) */
    target_agent_name?: string;
    /** Number of tasks (for parallel batch) */
    task_count?: number;
    /** Task details (for parallel batch) */
    tasks?: Array<{
      agent_id: string;
      prompt_preview: string;
    }>;
  };
}

/**
 * Validation response event payload.
 * Emitted after user approves or rejects a validation request.
 */
export interface ValidationResponseEvent {
  /** Validation request ID */
  validation_id: string;
  /** Whether approved (true) or rejected (false) */
  approved: boolean;
  /** Rejection reason if not approved */
  reason?: string;
}

/**
 * Validation event names for Tauri listeners.
 */
export const VALIDATION_EVENTS = {
  /** Event emitted when validation is required */
  VALIDATION_REQUIRED: 'validation_required',
  /** Event emitted when validation response is received */
  VALIDATION_RESPONSE: 'validation_response',
} as const;
