// Copyright 2025 Zileo-Chat-3 Contributors
// SPDX-License-Identifier: Apache-2.0

import type { Message } from './message';
import type { ThinkingStep } from './thinking';
import type { ToolExecution, WorkflowToolExecution } from './tool';

/**
 * Workflow status representing the current state of a workflow
 */
export type WorkflowStatus = 'idle' | 'running' | 'completed' | 'error';

/**
 * Workflow entity representing a user workflow
 */
export interface Workflow {
  /** Unique identifier */
  id: string;
  /** Workflow name */
  name: string;
  /** Associated agent ID */
  agent_id: string;
  /** Current status */
  status: WorkflowStatus;
  /** Creation timestamp */
  created_at: Date;
  /** Last update timestamp */
  updated_at: Date;
  /** Completion timestamp (if completed) */
  completed_at?: Date;
}

/**
 * Result of a workflow execution
 */
export interface WorkflowResult {
  /** Markdown report generated by the agent */
  report: string;
  /** Execution metrics */
  metrics: WorkflowMetrics;
  /** List of tools used during execution */
  tools_used: string[];
  /** List of MCP calls made during execution */
  mcp_calls: string[];
  /** Detailed tool execution data for persistence and display */
  tool_executions: WorkflowToolExecution[];
}

/**
 * Metrics collected during workflow execution
 */
export interface WorkflowMetrics {
  /** Duration in milliseconds */
  duration_ms: number;
  /** Input tokens consumed */
  tokens_input: number;
  /** Output tokens generated */
  tokens_output: number;
  /** Cost in USD */
  cost_usd: number;
  /** LLM provider used */
  provider: string;
  /** Model used */
  model: string;
}

/**
 * Complete workflow state for recovery after restart.
 *
 * Contains all data needed to fully restore a workflow session:
 * - The workflow metadata
 * - All conversation messages
 * - Tool execution history
 * - Thinking/reasoning steps
 *
 * Used by `load_workflow_full_state` command for Phase 5: Complete State Recovery.
 */
export interface WorkflowFullState {
  /** The workflow entity with metadata */
  workflow: Workflow;
  /** All messages in chronological order */
  messages: Message[];
  /** Tool execution history */
  tool_executions: ToolExecution[];
  /** Thinking/reasoning steps */
  thinking_steps: ThinkingStep[];
}
