// Copyright 2025 Assistance Micro Design
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Function Calling Types for JSON-based Tool Calling
//!
//! This module defines types for parsing and formatting tool calls using
//! the JSON function calling format (OpenAI standard) used by Mistral and Ollama.
//!
//! These types are used by the provider adapters (MistralToolAdapter, OllamaToolAdapter)
//! to convert between API-specific formats and our internal tool execution system.

use serde::{Deserialize, Serialize};

/// Represents a function/tool call extracted from an LLM response.
///
/// This is the parsed representation of a tool_call from the provider's JSON response.
/// The format follows the OpenAI function calling standard adopted by Mistral and Ollama.
///
/// # Example JSON (Mistral response)
/// ```json
/// {
///   "id": "call_abc123",
///   "type": "function",
///   "function": {
///     "name": "MemoryTool",
///     "arguments": "{\"operation\":\"add\",\"content\":\"test\"}"
///   }
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// Unique identifier for this call, generated by the provider.
    /// Mistral provides this; Ollama requires synthetic ID generation.
    pub id: String,

    /// Name of the function/tool to call.
    /// For local tools: "MemoryTool", "TodoTool"
    /// For MCP tools: "mcp__server__tool" format
    pub name: String,

    /// Parsed JSON arguments for the function call.
    /// Already deserialized from the API response.
    pub arguments: serde_json::Value,
}

impl FunctionCall {
    /// Checks if this is an MCP tool call (format: mcp__server__tool).
    pub fn is_mcp_tool(&self) -> bool {
        self.name.starts_with("mcp__")
    }

    /// Extracts MCP server and tool name from the function name.
    ///
    /// # Returns
    /// `Some((server_name, tool_name))` if this is an MCP tool, `None` otherwise.
    ///
    /// # Example
    /// ```ignore
    /// let call = FunctionCall {
    ///     id: "id".to_string(),
    ///     name: "mcp__serena__find_symbol".to_string(),
    ///     arguments: json!({}),
    /// };
    /// assert_eq!(call.parse_mcp_name(), Some(("serena", "find_symbol")));
    /// ```
    pub fn parse_mcp_name(&self) -> Option<(&str, &str)> {
        if !self.is_mcp_tool() {
            return None;
        }

        // Format: mcp__server__tool
        let stripped = self.name.strip_prefix("mcp__")?;
        let parts: Vec<&str> = stripped.splitn(2, "__").collect();
        if parts.len() == 2 {
            Some((parts[0], parts[1]))
        } else {
            None
        }
    }
}

/// Result of executing a function/tool call.
///
/// This is formatted and sent back to the LLM provider as a "tool" role message.
/// The format varies slightly between providers (handled by adapters).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCallResult {
    /// Corresponds to FunctionCall.id - links result to original call.
    pub call_id: String,

    /// Name of the function that was called (for reference).
    pub function_name: String,

    /// Whether the execution succeeded.
    pub success: bool,

    /// The result data from tool execution.
    /// This is the JSON output from our Tool::execute() method.
    pub result: serde_json::Value,

    /// Error message if success is false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,

    /// Execution time in milliseconds (for metrics).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_time_ms: Option<u64>,
}

impl FunctionCallResult {
    /// Creates a successful result.
    pub fn success(
        call_id: impl Into<String>,
        function_name: impl Into<String>,
        result: serde_json::Value,
    ) -> Self {
        Self {
            call_id: call_id.into(),
            function_name: function_name.into(),
            success: true,
            result,
            error: None,
            execution_time_ms: None,
        }
    }

    /// Creates a failure result with an error message.
    pub fn failure(
        call_id: impl Into<String>,
        function_name: impl Into<String>,
        error: impl Into<String>,
    ) -> Self {
        Self {
            call_id: call_id.into(),
            function_name: function_name.into(),
            success: false,
            result: serde_json::Value::Null,
            error: Some(error.into()),
            execution_time_ms: None,
        }
    }

    /// Sets the execution time in milliseconds.
    pub fn with_execution_time(mut self, ms: u64) -> Self {
        self.execution_time_ms = Some(ms);
        self
    }
}

/// Mode for tool/function selection in API calls.
///
/// Controls how the LLM should interact with available tools.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolChoiceMode {
    /// LLM decides whether to call tools or respond directly.
    #[default]
    Auto,

    /// LLM must call at least one tool.
    Required,

    /// LLM should not call any tools (respond directly).
    None,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_function_call_mcp_parsing() {
        // Local tool
        let local = FunctionCall {
            id: "call_1".to_string(),
            name: "MemoryTool".to_string(),
            arguments: json!({"operation": "add"}),
        };
        assert!(!local.is_mcp_tool());
        assert!(local.parse_mcp_name().is_none());

        // MCP tool
        let mcp = FunctionCall {
            id: "call_2".to_string(),
            name: "mcp__serena__find_symbol".to_string(),
            arguments: json!({"pattern": "Foo"}),
        };
        assert!(mcp.is_mcp_tool());
        assert_eq!(mcp.parse_mcp_name(), Some(("serena", "find_symbol")));

        // MCP tool with underscores in name
        let mcp2 = FunctionCall {
            id: "call_3".to_string(),
            name: "mcp__context7__get_docs".to_string(),
            arguments: json!({}),
        };
        assert!(mcp2.is_mcp_tool());
        assert_eq!(mcp2.parse_mcp_name(), Some(("context7", "get_docs")));
    }

    #[test]
    fn test_function_call_result_builders() {
        let success =
            FunctionCallResult::success("call_1", "MemoryTool", json!({"memory_id": "123"}));
        assert!(success.success);
        assert!(success.error.is_none());

        let failure = FunctionCallResult::failure("call_2", "TodoTool", "Database error");
        assert!(!failure.success);
        assert_eq!(failure.error, Some("Database error".to_string()));

        let with_time =
            FunctionCallResult::success("call_3", "Test", json!(null)).with_execution_time(150);
        assert_eq!(with_time.execution_time_ms, Some(150));
    }

    #[test]
    fn test_tool_choice_mode() {
        // Verify the production serde serialization (snake_case) sent to APIs.
        assert_eq!(
            serde_json::to_value(ToolChoiceMode::Auto).unwrap(),
            json!("auto")
        );
        assert_eq!(
            serde_json::to_value(ToolChoiceMode::Required).unwrap(),
            json!("required")
        );
        assert_eq!(
            serde_json::to_value(ToolChoiceMode::None).unwrap(),
            json!("none")
        );

        // Test default
        assert_eq!(ToolChoiceMode::default(), ToolChoiceMode::Auto);
    }
}
